
version: '3'
services:
  game_api:
    image: orria16/hgop:${GIT_COMMIT}
    ports:
    - '3000:3000'
    depends_on:
    - my_database_container
    environment:
      PORT: 3000
      POSTGRES_HOST: 'my_database_container'
      POSTGRES_DB: 'game_postgres_database'
      POSTGRES_USER: 'my_postgres_user'
      POSTGRES_PASSWORD: 'my_postgres_password'
  my_database_container:
    image: postgres
    environment:
      POSTGRES_DB: 'game_postgres_database'
      POSTGRES_USER: 'my_postgres_user'
      POSTGRES_PASSWORD: 'my_postgres_password'   